### ISSUE TITLE
need documentation for 'tokens', and remove magic import

### ISSUE THREAD

**Issue by koreno** [weka-io/easypy#112]

**Comment by DoronCohen** [comment]
I would suggest to use the tokens modules as:

    from easypy.tokens import Token
    AUTO = Token('AUTO')
    MAX = Token('MAX')

we could allow magic import but it's implementation should also use the `Token` class as above. that way we make it super easy for others to understand what is happening.

**Comment by koreno** [comment]
fixed by #123
