### ISSUE TITLE
Better lockstep API

### ISSUE THREAD

**Issue by idanarye** [weka-io/easypy#13]
@koreno - what's our policy regarding breaking changes in easypy?

[You wanted to add `process.execute()`](https://github.com/weka-io/easypy/pull/9#discussion_r112005932) to ease the execution without stepping into the process. We decided against it because it's not super-trivial(we can't just put a method on the wrapper - it won't get bound to the object) and because we want the non-stepping invocation to be a direct method of the object, so we'd still need a wrapper method - which kind of nullifies the benefit of `process.execute()`.

But what if we reverse it? Instead of:

```python
@lockstep
def my_process_lockstep():
    # ...

# step-by-step
with my_process_lockstep() as process:
    # ...

# just do it
my_process_lockstep.execute()
```

We'll do this:
```python
@lockstep
def my_process():
    # ...

# step-by-step
with my_process.lockstep() as process:
    # ...

# just do it
my_process()
```

We'll still need our own property descriptor, but we'll have the benefit of having the direct execution as the main API, which will save us the need for a wrapper method.

**Comment by koreno** [comment]
I like it very much.
At this point I'm not concerned about breaking changes... go for it
