### ISSUE TITLE
Based unnamed thread names on named threads

### ISSUE THREAD

**Issue by idanarye** [weka-io/easypy#174]
There are three "styles" of thread names:
* Unnamed threads - get the name Python assigns to them ("Thread-1234")
* Arbitrarily named threads - created with `concurrent()`, get names like "anon-7F4A1EE18A20".
    * For some reason `concurrent` creates them but `concurrent_map` - which `MultiObject` uses - does not. @koreno - was there a particular reason for that? Why did you rename these threads in the first place?
* Named threads - which we purposefully give names to ("wd-my-watchdog-thread")

Named threads are usually used for macro scale processes (like watchdogs or mayhem actions). The problem is that when they need to "split up" they get arbitrary names making it harder to associate log lines to them.

I think you should use the following rule:

1. If a thread is explicitly named - use that name.
2. Otherwise, go up the thread tree to find a named thread, and append some random/incrementing subidentifier to it ("wd-my-watchdog:AABBCC")
    * Instead of scaling the tree, we can just put the named thread's name in the thread context.
3. If there is no named thread ancestor - use a generic name.

This will improve the ability to read the logs.

c.c. @DoronCohen @YuvalEvron

**Comment by koreno** [comment]
Good idea!
