### ISSUE TITLE
Improve infinite recursion exception when aliasing

### ISSUE THREAD

**Issue by idanarye** [weka-io/easypy#210]
Aliasing should catch the `RecursionError` and emit a better error that tells you about the object, the aliased object, and the attribute.

**Comment by koreno** [comment]
do show an example, I've never run into one of those...

**Comment by idanarye** [comment]
```python
from easypy.aliasing import aliases


@aliases('bar', static=False)
class Foo:
    def __init__(self):
        self.bar = Bar(self)


class Bar:
    def __init__(self, foo):
        self.foo = foo

    def baz(self):
        return self.foo.baz()


print(Foo().baz())
```

These things do happen occasionally in the wild, when the code is more complex and have more moving parts, and are quite difficult to debug.
