### ISSUE TITLE
The case for EasyMeta

### ISSUE THREAD

**Issue by idanarye** [weka-io/easypy#80]
We use a lot of metaclasses:

| Meta Class | What it does |
| -------------- | ---------------- |
| `easypy.concurrency.MultiExceptionMeta` | Generate subtypes with generics syntax |
| `easypy.concurrency.SynchronizedSingleton` | Make all instances of each subclass share the same object, thread safe |
| `easypy.typed_struct.TypedStructMeta` | DSL for declaring typed structs |
| `wepy.aws.instance_types.InstanceTypeMeta` | Not really sure... @koreno / @DoronCohen? |
| `wepy.devops.cluster.setup.ReplaceWithOuter` | @tigrawap? |
| `wepy.devops.jira.JiraProjectMeta` | Register the subclasses |
| `wepy.devops.roles.RoleMeta` | Make subclasses behave like objects, not types |
| `wepy.devops.roles.HostRoleMeta` | Inherits `RoleMeta` and does some trivial setup on top of it |
| `wepy.devops.triage.TriagePluginMeta` | Register the subclasses (unless a `SHOULD_RUN` field is set) |
| `wepy.explore.faults.FaultsMeta` | Decorate methods |
| `qa.mayhem.mayhem_actions.MayhemActionMeta` | Register the subclasses (unless they are abstract) and does some field verification and auto-setting |
| `qa.testlight.system_setup._ABCMetaWithLRUCache` | Cache all instances of each subclass constructed with the same parameters |
| `qa.testlight.utils.ParametrizedBehaviorFixture` | DSL for creating a pytest fixture (not a type!) |

`ParametrizedBehaviorFixture` does not create a type, so it should remain it's own metaclass.

`RoleMeta`/`HostRoleMeta` are data notation - they would benefit from the discussion at https://github.com/weka-io/black-magic/issues/1

For everything else on the list (except `InstanceTypeMeta` and `ReplaceWithOuter`, which I didn't really understand what they do), I want to create a new module - `easypy.meta` - with a metaclass named `EasyMeta` that will contain all these features:
* Automatic class registration
* Subclass verification/modification
* Automatic method decoration
* Easy DSL definitions

The reason for using a single metaclass is that multi-inheritance does not work well with different metaclasses.

----------------

My grepping also found these:
```
$ git grep 'a metaclass could make this go away...'

wepy/devops/jobs/coverage/__init__.py:TestDefinitionRow.table_cls.DATA_CLS = TestDefinitionRow  # a metaclass could make this go away...
wepy/devops/jobs/coverage/__init__.py:JobExecutionRow.table_cls.DATA_CLS = JobExecutionRow  # a metaclass could make this go away...
wepy/devops/jobs/coverage/__init__.py:TestExecution.table_cls.DATA_CLS = TestExecution  # a metaclass could make this go away...
```
We can probably add that functionality to `EasyMeta` too.

**Comment by koreno** [comment]
sounds nice.
show 2-3 applications to what you come up with, so we can assess.

**Comment by idanarye** [comment]
The most basic will be the ability to move `__init__`,  `__new__` and `__call__` from the metaclass to the class itself, so that instead of:
```python
class JiraProjectMeta(type):
    def __init__(cls, name, parents, dct):
        if set(parents) - {object}:
            JiraProject.PROJECTS[name] = cls
        super().__init__(name, parents, dct)
```

We could just do it in the class:
```python
class JiraProject(metaclass=EasyMeta):
    @classmethod
    def _em_subclass_init_(cls, name, parents, dct):
        if set(parents) - {object}:
            JiraProject.PROJECTS[name] = cls
        super()._em_subclass_init_(name, parents, dct)
```

Note that I'm calling it `_em_subclass_init_` instead of `_em_init_` so that it won't get called on `JiraProject`.

Next: replace this:

```python
class SynchronizedSingleton(type):
    _instances = {}

    @synchronized
    def __call__(cls, *args, **kwargs):
        if cls not in cls._instances:
            cls._instances[cls] = super().__call__(*args, **kwargs)

        return cls._instances[cls]

    @synchronized
    def get_instance(cls):
        return cls._instances.get(cls)
```

With this:
```python
class SynchronizedSingleton(metaclass=EasyMeta):
    __instances = {}

    # Be able to call SynchronizedSingleton.get_instance, but not
    # Foo.get_instance if Foo is a subclass of SynchronizedSingleton.
    @EasyMeta.dont_inherit
    @synchronized
    def get_instance(cls):
        return cls.__instances.get(cls)

    @classmethod
    @synchronized
    def _em_subclass_call_(cls, *args, **kwargs):
        if cls not in cls.__instances:
            cls.__instances[cls] = super()._em_subclass_call_(*args, **kwargs)

        return cls.__instances[cls]
```

The benefit is that now if we want a class to be a `SynchronizedSingleton` and have some other metaclass abilities - we can do it with multiple inheritance, without having to create a new metaclass.

Also, instead of this:
```python
class FaultsMeta(type):
    def __new__(meta, name, parents, dct):
        if dct['__module__'] != FaultsMeta.__module__:  # don't decorate the base Faults object
            for k, v in dct.items():
                if (not k.startswith('_')  # don't log protected&private helper methods
                    and k not in Faults.__dict__  # don't log the base Faults methods
                    and isinstance(v, FunctionType)  # don't log static and class methods
                    ):
                    dct[k] = _decorate_with_logging(k, v)
        return super().__new__(meta, name, parents, dct)
```

We could have this:
```python
class Faults(Component, metaclass=EasyMeta):  # or maybe Component will already use EasyMeta?
    class DSL(EasyMeta.DSL):
        def __setitem__(self, name, value):
            if (
                    not name.startswith('_')  # don't log protected&private helper methods
                    and isinstance(value, FunctionType)  # don't log static and class methods
            ):
                value = _decorate_with_logging(name, value)
        return super().__setitem__(name, value)
```

Or even this:
```python
class Faults(Component, metaclass=EasyMeta):
    @staticmethod
    def _em_dsl_process_item_(name, value):
        if (
                not name.startswith('_')  # don't log protected&private helper methods
                and isinstance(value, FunctionType)  # don't log static and class methods
        ):
            value = _decorate_with_logging(name, value)
        return (name, value)
```

Note that this changes the behavior a little - instead of doing the decoration after the class dict is prepared and before the class object is created, we do it immediately when the method is declared. This also means we don't have to check that the method is not from the base `Faults` class - it will only be called on the fields declared in the subclass (**when** they are declared in the subclass)

We can go even farther:

```python
class Faults(Component, metaclass=EasyMeta):
    EasyMeta.auto_decorate(
        decorator=_decorate_with_logging,
        pred=lambda fld: (
            not fld.__name__.startswith('_')  # don't log protected&private helper methods
            and isinstance(fld, FunctionType)  # don't log static and class methods
        ))
```

**Comment by DoronCohen** [comment]
auto class registration will make our code a lot cleaner

**Comment by idanarye** [comment]
BTW - once we have `EasyMeta` we would probably not use it directly, and instead have mixin classes. For example:

```python
class JiraProject(AutoRegister):
    PROJECTS = {}
    _ar_register_at_ = PROJECTS
    _ar_skip_this_ = True  # Avoid registering this particular class. Will not be inherited by subclasses
```

Or maybe, instead of mixins, we could have a plugin system:
```python
class JiraProject(metaclass=EasyMeta):
    PROJECTS = {}
    _em_plugins_.append(AutoRegister(at=PROJETS, skip_this=True))  # actually, skip_this=True should be the default
```
